// vue-frontend/src/App.vue
<template>
  <div id="app">
    <todo-creator :add-todo="addTodo" />
    <todo-list :todos="todos" :remove-todo="removeTodo" :toggle-todo="toggleTodo" />
  </div>
</template>

<script>
import Axios from "axios";
import TodoCreator from "./components/TodoCreator";
import TodoList from "./components/TodoList";

export default {
  name: "app",
  components: {
    TodoList,
    TodoCreator
  },
  data() {
    return {
      todos: []
    };
  },
  methods: {
    addTodo(event, action) {
      event.preventDefault();

      const url = `http://localhost:8080/api/todo`;
      const config = {
        headers: {
          "Content-Type": "application/x-www-form-urlencoded"
        }
      };
      Axios.post(url, `action=${action}`, config).then(
        this.todos.push({ action, done: false })
      );
    },
    removeTodo(index) {
      Axios.delete(`http://localhost:8080/api/todo/${index + 1}`).then(
        (this.todos = this.todos.filter((_, i) => i !== index))
      );
    },
    toggleTodo(index) {
      Axios.post(`http://localhost:8080/api/todo/toggle/${index + 1}`).then(
        (this.todos = this.todos.map((item, idx) =>
          idx !== index ? item : { ...item, done: !item.done }
        ))
      );
    }
  },
  created() {
    Axios.get("http://localhost:8080/api/todo").then(
      response => (this.todos = response.data)
    );
  }
};
</script>

<style>
</style>

// react-frontend/src/App.js
import React, { Component } from 'react';
import { TodoCreator } from './TodoCreator';
import { TodoList } from './TodoList';
import Axios from 'axios';

class App extends Component {
  url = 'http://localhost:8080/api/todo';

  constructor(props) {
    super(props);
    this.state = {
      todos: []
    };
  }

  componentDidMount = _ => {
    document.title = 'Todo App';

    Axios.get(this.url).then(response =>
      this.setState({ todos: response.data })
    );
  };

  toggleTodo = position => {
    const mapper = (item, index) =>
      position === index ? { ...item, done: !item.done } : item;
    Axios.post(`${this.url}/toggle/${position + 1}`).then(_ =>
      this.setState({
        todos: this.state.todos.map(mapper)
      })
    );
  };

  removeTodo = position => {
    Axios.delete(`${this.url}/${position + 1}`).then(_ =>
      this.setState({
        todos: this.state.todos.filter((_, index) => position !== index)
      })
    );
  };

  addTodo = action => {
    const config = {
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded'
      }
    };
    Axios.post(this.url, `action=${action}`, config).then(_ =>
      //TODO 不判断action是否已经存在
      this.setState({ todos: [...this.state.todos, { action, done: false }] })
    );
  };

  render = _ => (
    <div>
      <TodoCreator addTodo={this.addTodo} />
      <TodoList
        todos={this.state.todos}
        toggleTodo={this.toggleTodo}
        removeTodo={this.removeTodo}
      />
    </div>
  );
}

export default App;
